apiVersion: apps/v1
kind: Deployment
metadata:
  name: grilli-deployment
  labels:
    app: grilli-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grilli-app
  template:
    metadata:
      labels:
        app: grilli-app
    spec:
      imagePullSecrets:
      - name: ecr-regcred
      containers:
      - name: grilli-container
        image: 873727239305.dkr.ecr.ap-southeast-2.amazonaws.com/grilli-repo:latest
        ports:
        - containerPort: 80
